### ISSUE TITLE
Wheels on PyPI

### ISSUE THREAD

**Issue by frenzymadness** [karlb/sqlite-icu#2]
Hi. Thanks for the great project!

Have you considered publishing wheels on PyPI so users don't have to compile the extension from sources? It might be useful mainly for containerized applications where you don't have packages like sqlite-devel libicu-devel or gcc installed.

If you want to, I can help you with that.

**Comment by karlb** [comment]
I could upload a wheel built on my debian linux machine. But I assume most users would need a different wheel for they choice of OS and python version.

PRs to provide wheels in a systematic way are welcome, as long as they stay somewhat simple!

**Comment by frenzymadness** [comment]
I can prepare a script that would use [manylinux container image](https://github.com/pypa/manylinux) and provides universal manylinux wheels (2014) for all supported Python versions. Does that sound good to you?

**Comment by karlb** [comment]
Yes, that sound good.

**Comment by frenzymadness** [comment]
I'm taking a look at it and we have two possibilities:
* A script using docker/podman and manylinux container images to produce universal wheels. You'd need to run the script manually on your machine for each release and then you'd upload all the wheels together with the sdist.
* Set up a CI job with [cibuildwheel](https://github.com/pypa/cibuildwheel#usage) which would build all the wheels for you in Github actions for every new commit. Then, you'd just need to download the wheels and upload them to PyPI. It should be also possible to automate the release process entirely, if you want to.

What do you prefer?

**Comment by karlb** [comment]
Thanks for investigation! Both approaches sound fine to me. If you don't have a preference, let's choose the second one.
