### ISSUE TITLE
Wheel for new Pythons

### ISSUE THREAD

**Issue by frenzymadness** [karlb/sqlite-icu#5]
Hi.

Would it be possible to build and publish wheels for newer Pythons 3.11+? If you want, I can help you build them or set up a CI job that would do it for you.

**Comment by karlb** [comment]
I could build new wheels, but a CI job that builds for multiple Python
versions and architectures would be an improvement. If you'd like to give
it a try, please go ahead!

**Comment by frenzymadness** [comment]
Well, it seems I have the same idea two years ago and implemented it already: https://github.com/karlb/sqlite-icu/commit/b085bf5f9b7aa5a87a12a7ca16c2e7b7dbb22d27 

I think you can try to open a PR with a version bump and that should build all the wheels you can then upload to PyPI.

**Comment by karlb** [comment]
Haha, that's an excellent point! Thanks! I updated the cibuildwheels version and uploaded packages for the new python versions to PyPI.
